### ISSUE TITLE
fs.copyFile is not a function

### ISSUE THREAD

**Issue by cczw2010** [mimecorg/launchui-packager#3]
>launchui-packager hello 1.0.0 examples/area-adv.js --out ../

Packaging hello version 1.0.0 for darwin-x64
Extracting launchui-v0.1.4-darwin-x64.zip
/usr/local/lib/node_modules/launchui-packager/index.js:203
    fs.copyFile( entry, destPath, error => {
       ^

TypeError: fs.copyFile is not a function
    at copyEntryScript (/usr/local/lib/node_modules/launchui-packager/index.js:203:8)
    at copyIcns (/usr/local/lib/node_modules/launchui-packager/index.js:193:7)
    at fs.rename.error (/usr/local/lib/node_modules/launchui-packager/index.js:160:9)
    at FSReqWrap.oncomplete (fs.js:135:15)

**Comment by cczw2010** [comment]
my node is 8.1.2  . when  update to 10.x  fixed it.

**Comment by mimecorg** [comment]
That's correct, fs.copyFile requires Node.js 8.5 or newer.
